version: '3.8'

services:
  youtube-bot:
    build: .
    container_name: youtube-discord-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=UTC 